/**
 * JobPortal Admin Production
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDropDownModel { 
    clientCompanyName?: string | null;
    jobTitle?: string | null;
    id?: string;
}

